version: '3'
services:
  log4j_server:
    image: log4j_server:latest
    ports:
      - 4561:4560
    volumes:
      - ./my_app:/app
      - ./log4j/config:/usr/log4j/config
    command: ["/bin/sh","log4j-server-start.sh"]
  tomcat_server:
    image: apsl/tomcat6:latest
    ports:
      - 8081:8080
    environment:
      - MANAGER_USER=admin
      - MANAGER_PASSWORD=1234
    volumes:
      - ./my_app:/app


